version: '1'
services:
  y_lab_web:
    container_name: y_lab_web
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    entrypoint: sh -c "alembic upgrade head && uvicorn main:app --host y_lab_web --port 8000"
    restart: always
    links:
      - db:db
    networks:
      - y_lab_networks
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    container_name: db
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - y_lab_networks
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]

networks:
  y_lab_networks:
    name: y_lab_network
volumes:
  database_volume: