version: "1.1"
services:
  y_lab_tests:
    container_name: y_lab_tests
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db_test
    entrypoint: sh -c "alembic upgrade head && pytest"
    volumes:
      - shared-volume:/app/generated_files
    networks:
      - y_lab_network
    links:
      - db_test:db_test
    depends_on:
      db_test:
        condition: service_healthy
    tty: true

  db_test:
    container_name: db_test
    image: postgres:15.1-alpine
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - y_lab_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s


networks:
  y_lab_network:
    name: y_lab_network
volumes:
  postgres_data:
  shared-volume: