"""Fix migration

Revision ID: 16237bb11024
Revises: 4eb935f20af6
Create Date: 2024-01-21 22:21:31.015489

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '16237bb11024'
down_revision: str | None = '4eb935f20af6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
