"""Fix migration

Revision ID: 6dfd39bc8082
Revises: 795bf491c686
Create Date: 2024-01-22 00:35:35.658531

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '6dfd39bc8082'
down_revision: str | None = '795bf491c686'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
