"""Fix migration

Revision ID: 795bf491c686
Revises: ffb2190a0918
Create Date: 2024-01-21 22:42:18.784537

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '795bf491c686'
down_revision: str | None = 'ffb2190a0918'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
