"""Fix migration 3

Revision ID: c375a20dd5b5
Revises: 6dfd39bc8082
Create Date: 2024-01-22 14:55:40.428767

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c375a20dd5b5'
down_revision: str | None = '6dfd39bc8082'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
