"""Fix migration 4

Revision ID: fab45af2fe55
Revises: c375a20dd5b5
Create Date: 2024-01-22 14:59:32.890562

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fab45af2fe55'
down_revision: str | None = 'c375a20dd5b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
