"""Fix migration

Revision ID: ffb2190a0918
Revises: 16237bb11024
Create Date: 2024-01-21 22:35:36.611084

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ffb2190a0918'
down_revision: str | None = '16237bb11024'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
